[DNM] Allow running browser tests locally
This currently fails with

Error: An error occurred while trying to start the Nightwatch Runner: Cannot find module '/app/nightwatch.config.js'

The cause is yet to be determined.